from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from mcp.server.fastmcp import FastMCP

from mcp_notebooks.models.schema import (
    StartKernelResponse,
    CodeSnippet,
    ExecuteResponse,
    ShutdownResponse,
    GetNotebookResponse,
)
from mcp_notebooks.core.manager import SessionManager, SessionNotFoundError
from mcp_notebooks.app.exception_handler import register_exception_handlers

mcp = FastMCP("mcp_notebooks", dependencies=["jupyterlab", "fastapi"])
app = FastAPI()
register_exception_handlers(app)
session_manager = SessionManager()


@app.post("/start", response_model=StartKernelResponse)
@mcp.tool("start", description="Start a new Jupyter kernel session")
def start_kernel() -> StartKernelResponse:
    """
    Start a new Jupyter kernel session.

    Returns:
        A unique session ID and a message indicating the session was successfully created.
    """

    session_id = session_manager.create_session()
    return StartKernelResponse(session_id=session_id, message="success")


@app.post("/execute", response_model=ExecuteResponse)
@mcp.tool("execute", description="Execute code in a Jupyter kernel session")
def execute_code(snippet: CodeSnippet) -> ExecuteResponse:
    """
    Execute a code snippet in the specified kernel session.

    Args:
        snippet: A CodeSnippet object containing the session ID and code to run.

    Returns:
        Outputs generated by the code execution and the execution count.
    """

    session = session_manager.get_session(snippet.session_id)
    response = session.execute(snippet.code)

    return ExecuteResponse(
        outputs=response.outputs, execution_count=response.execution_count
    )


@app.post("/get_notebook/{session_id}")
@mcp.tool(
    "get_notebook",
    description="Get notebook contents from a Jupyter kernel session",
)
def get_notebook(session_id: str) -> GetNotebookResponse:
    """
    Shut down an active kernel session and return its notebook contents.

    Args:
        session_id: The ID of the kernel session get the notebook from.

    Returns:
        A dictionary containing the notebook contents accumulated during the session.
    """

    session = session_manager.get_session(session_id)
    notebook = session.get_notebook()

    return GetNotebookResponse(notebook=notebook)


@app.post("/shutdown/{session_id}")
@mcp.tool("shutdown", description="Shut down a Jupyter kernel session")
def shutdown_kernel(session_id: str) -> ShutdownResponse:
    """
    Shut down an active kernel session and return its notebook contents.

    Args:
        session_id: The ID of the kernel session to shut down.

    Returns:
        A dictionary containing the notebook contents accumulated during the session.
    """

    output = session_manager.delete_session(session_id)
    return ShutdownResponse(
        message="success",
        notebook=output,
    )


@app.post("/notebook-running/{session_id}")
@mcp.resource(
    "notebook-running://{session_id}",
    description="Check if a Jupyter kernel session is running",
)
def notebook_running(session_id: str) -> bool:
    """
    Show whether a notebook session is still running.

    Args:
        session_id: The ID of the kernel session get the notebook from.

    Returns:
        A dictionary containing the notebook contents accumulated during the session.
    """
    try:
        session_manager.get_session(session_id)
        return True
    except SessionNotFoundError:
        return False


@app.get("/")
async def redirect_docs():
    return RedirectResponse("/docs")
